### PR TITLE
consider agent when explicitly defined when associating backends

### LINKED ISSUE #32: Fix ambiguous backend association when using regex-based classes
**Describe the bug**
When using regular expressions as `className` while defining the available backends, the association to the corresponding agent may get mixed up if backend would as well match the regular expression.

**To Reproduce**
Define for example:

```javascript
const VrpcProvider = createVrpcProvider({
  domain: 'public.vrpc',
  backends: {
    one: {
      agent: 'agent1',
      className: /Foo.*/
    }
    two: {
      agent: 'agent2',
      className: /Foo.*/
    }
  }
})
```
Then, if an agent provides the class `FooTest`, its instance will be associated to the first backend found, and not the one with the corresponding agent.

**Expected behavior**
When an agent is explicitly set the association must not be ambiguous.

### PR DESCRIPTION
**Pull request by bheisen**
# Changes proposed in the pull request:

Associates proper backend when agent is explicitly defined

closes #32

### CODE REVIEW

**Review by benjamin-joham — COMMENTED** [review]
This does not include the vrpc version update. Will this be handled in a seperate PR?

**Comment by bheisen** [comment]
good point, updated the vrpc peer dependency and bumped all other versions

**Review by benjamin-joham — CHANGES_REQUESTED** [review]
Nice work, I would like to test this tomorrow morning with multiple backends before we merge that.

**Comment by benjamin-joham** [comment]
@bheisen we should also bump the vrpc version in the examples and maybe use the local src/react-vrpc.js file as dependency in there for easier debugging.
`"react-vrpc": "file:../../../src/react-vrpc"`

**Comment by bheisen** [comment]
Ok, I will do that quickly. But beware that using the local package option still creates a copy. So, if you want to tightly develop on the examples you should replace the `node_modules/react-vrpc` with a sym-link or use npm link.

**Review by benjamin-joham — APPROVED** [review]

**Pull request merged**
